"""add division model and grade_group division_id

Revision ID: 0d6f352d92dd
Revises: d5859254aa1f
Create Date: 2026-04-28 15:26:56.466782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6f352d92dd'
down_revision = 'd5859254aa1f'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'division' not in existing_tables:
        op.create_table('division',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    if 'teacher_day_override' not in existing_tables:
        op.create_table('teacher_day_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['conference_day.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_id', 'teacher_id')
    )
    cd_cols = [c['name'] for c in inspector.get_columns('conference_day')]
    if 'division_id' not in cd_cols:
        with op.batch_alter_table('conference_day', schema=None) as batch_op:
            batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_conference_day_division', 'division', ['division_id'], ['id'], ondelete='SET NULL')

    gg_cols = [c['name'] for c in inspector.get_columns('grade_group')]
    if 'division_id' not in gg_cols:
        with op.batch_alter_table('grade_group', schema=None) as batch_op:
            batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_grade_group_division', 'division', ['division_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grade_group_division', type_='foreignkey')
        batch_op.drop_column('division_id')

    with op.batch_alter_table('conference_day', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conference_day_division', type_='foreignkey')
        batch_op.drop_column('division_id')

    op.drop_table('teacher_day_override')
    op.drop_table('division')
    # ### end Alembic commands ###
