"""add grade_group_subject

Revision ID: 69fdedcccca3
Revises: 87ca89513e56
Create Date: 2026-04-25 10:24:19.894133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fdedcccca3'
down_revision = '87ca89513e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_group_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_group_id'], ['grade_group.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_group_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_group_subject')
    # ### end Alembic commands ###
