"""add_is_active_to_conference_day

Revision ID: b10150f75d1e
Revises: 611e7b4d6bbb
Create Date: 2026-04-27 08:54:43.604939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10150f75d1e'
down_revision = '611e7b4d6bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_day', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
